In [18]:
import numpy as np

### Create an Array

In [19]:
arr = np.array([1,2,3,4,5]) #Row Matrix
arr2 = np.array([[1],[2],[3]]) #Column Matrix
print(arr)
print(arr2)
print(type(arr))
print("\n")
print(np.dtype)
print("\n")
print(np.ndim(arr))
print("\n")
print(type(arr))
print("\n")
print(arr.shape)

[1 2 3 4 5]
[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>


<class 'numpy.dtype'>


1


<class 'numpy.ndarray'>


(5,)


### Multidimensional Array

In [20]:
matrix = np.array([[1,2],[3,4]])
print(matrix)
print(matrix.shape)

[[1 2]
 [3 4]]
(2, 2)


### Array Operations

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)     # Square

[5 7 9]
[ 4 10 18]
[1 4 9]


### Useful Array Functions

In [22]:
arr3 = np.arange(1,21)
print(arr3)

print(np.mean(arr3))    # Average
print(np.std(arr3))     # Standard deviation
print(np.sum(arr3))     # Sum
print(np.max(arr3))     # Max
print(np.min(arr3))     # Min


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
10.5
5.766281297335398
210
20
1


### Indexing and slicing

In [25]:
arr_2D = arr3.reshape(5,4)
print(arr_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [28]:
print(arr_2D[1][1]) # Single element
print(arr_2D[0])    #Single Row
print(arr_2D[:, 0])  #Single Column

6
[1 2 3 4]
[ 1  5  9 13 17]


### Special Arrays

In [8]:
print(np.zeros((2, 3)))       # 2x3 array of zeros
print(np.ones((3, 3)))        # 3x3 array of ones
print(np.eye(3))              # Identity matrix
print(np.arange(0, 10, 2))    # [0 2 4 6 8]
print(np.linspace(0, 1, 5))   # 5 values from 0 to 1


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Reshaping Arrays

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape((2, 3))  # Now 2 rows, 3 columns
print(a)


[[1 2 3]
 [4 5 6]]


### Matrix Operations

In [45]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(A @ B)       #Matrix Multiplication
print("Transpose of A\n", A.T)
print("Inverse of B =\n", np.linalg.inv(B))

[[ 4  4]
 [10  8]]
Transpose of A
 [[1 3]
 [2 4]]
Inverse of B =
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]


### Particle Velocity

In [52]:
velocities = np.array([3.5, 4.0, 2.8, 5.2, 3.9])
m = 2
KE = 1/2 * m * (velocities ** 2)
print("Kinetic Energies:",KE)
avg_KE = np.mean(KE)
rounded_average = round(avg_KE, 2)
print("Average of the kinetic energies", rounded_average)

Kinetic Energies: [12.25 16.    7.84 27.04 15.21]
Average of the kinetic energies 15.67


## Linear Algebra

### Matrix multiplication

In [1]:
import numpy as np

In [2]:
a = np.ones((2,3))
b = np.full((3,2),3)    # make a 3 x 2 matrix with 3
print(a)
print(b)


c = np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[9. 9.]
 [9. 9.]]


### Solve a system of linear equations
    3x + 2y  = 16, 4x - y = 9

In [9]:
A = np.array([[3,2],[4,-1]])
print(A)
print("\n")
b = np.array([16,9])
print(b)
print("\n")
x = np.linalg.solve(A,b)
print(x)

[[ 3  2]
 [ 4 -1]]


[16  9]


[3.09090909 3.36363636]
