In [18]:
import numpy as np

### Create an Array

In [19]:
arr = np.array([1,2,3,4,5]) #Row Matrix
arr2 = np.array([[1],[2],[3]]) #Column Matrix
print(arr)
print(arr2)
print(type(arr))
print("\n")
print(np.dtype)
print("\n")
print(np.ndim(arr))
print("\n")
print(type(arr))
print("\n")
print(arr.shape)

[1 2 3 4 5]
[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>


<class 'numpy.dtype'>


1


<class 'numpy.ndarray'>


(5,)


### Multidimensional Array

In [20]:
matrix = np.array([[1,2],[3,4]])
print(matrix)
print(matrix.shape)

[[1 2]
 [3 4]]
(2, 2)


### Array Operations

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)     # Square

[5 7 9]
[ 4 10 18]
[1 4 9]


### Useful Array Functions

In [22]:
arr3 = np.arange(1,21)
print(arr3)

print(np.mean(arr3))    # Average
print(np.std(arr3))     # Standard deviation
print(np.sum(arr3))     # Sum
print(np.max(arr3))     # Max
print(np.min(arr3))     # Min


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
10.5
5.766281297335398
210
20
1


### Indexing and slicing

In [25]:
arr_2D = arr3.reshape(5,4)
print(arr_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [28]:
print(arr_2D[1][1]) # Single element
print(arr_2D[0])    #Single Row
print(arr_2D[:, 0])  #Single Column

6
[1 2 3 4]
[ 1  5  9 13 17]


### Special Arrays

In [8]:
print(np.zeros((2, 3)))       # 2x3 array of zeros
print(np.ones((3, 3)))        # 3x3 array of ones
print(np.eye(3))              # Identity matrix
print(np.arange(0, 10, 2))    # [0 2 4 6 8]
print(np.linspace(0, 1, 5))   # 5 values from 0 to 1


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Reshaping Arrays

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape((2, 3))  # Now 2 rows, 3 columns
print(a)


[[1 2 3]
 [4 5 6]]


### Matrix Operations

In [45]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(A @ B)       #Matrix Multiplication
print("Transpose of A\n", A.T)
print("Inverse of B =\n", np.linalg.inv(B))

[[ 4  4]
 [10  8]]
Transpose of A
 [[1 3]
 [2 4]]
Inverse of B =
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]


### Particle Velocity

In [52]:
velocities = np.array([3.5, 4.0, 2.8, 5.2, 3.9])
m = 2
KE = 1/2 * m * (velocities ** 2)
print("Kinetic Energies:",KE)
avg_KE = np.mean(KE)
rounded_average = round(avg_KE, 2)
print("Average of the kinetic energies", rounded_average)

Kinetic Energies: [12.25 16.    7.84 27.04 15.21]
Average of the kinetic energies 15.67


## Linear Algebra

### Matrix multiplication

In [1]:
import numpy as np

In [2]:
a = np.ones((2,3))
b = np.full((3,2),3)    # make a 3 x 2 matrix with 3
print(a)
print(b)


c = np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[9. 9.]
 [9. 9.]]


### Solve a system of linear equations
    3x + 2y  = 16, 4x - y = 9

In [9]:
A = np.array([[3,2],[4,-1]])
print(A)
print("\n")
b = np.array([16,9])
print(b)
print("\n")
x = np.linalg.solve(A,b)
print(x)

[[ 3  2]
 [ 4 -1]]


[16  9]


[3.09090909 3.36363636]


## Random Numbers

### Random Integers

In [32]:
import numpy as np
np.random.seed(0)
rolls = np.random.randint(1,7, size = 10)
print(rolls)

[5 6 1 4 4 4 2 4 6 3]


### Uniform distribution between 0 and 1

In [33]:
uniform_vals = np.random.rand(5)
print("Uniform [0, 1):", uniform_vals)


Uniform [0, 1): [0.43758721 0.891773   0.96366276 0.38344152 0.79172504]


### Normal Distribution

In [34]:
normal_vals = np.random.randn(5)
print("Standard Normal (mean=0, std=1):", normal_vals)


Standard Normal (mean=0, std=1): [ 2.54520078  1.08081191  0.48431215  0.57914048 -0.18158257]


### Choose random elements from a list

In [35]:
choices = np.random.choice([10, 20, 30, 40, 30,45,55,69,50,34,90], size=5)
print("Random choices:", choices)


Random choices: [40 40 69 10 20]


### Shuffle an array

In [36]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:", arr)


Shuffled array: [3 4 1 5 2]


### Practice

In [48]:
# Generate a 3 x 4 matrix of random integers between 50 and 100

import numpy as np

random_matrix = np.random.randint(50,101,size = 12)
random_matrix_2D = random_matrix.reshape(3,4)
print(random_matrix_2D)

[[96 92 90 63]
 [80 74 52 53]
 [80 84 93 63]]


### Temperature sensor simulation

In [10]:
import numpy as np

In [26]:
np.random.seed(0)
temp_array = np.random.uniform(-10, 40,size = 100) # Generated 100 random number between -10 an 40
print(temp_array)

[17.4406752  25.75946832 20.1381688  17.24415915 11.18273997 22.29470565
 11.87936056 34.58865004 38.18313803  9.17207594 29.5862519  16.44474599
 18.40222805 36.27983191 -6.44819709 -5.64353501 -8.98908013 31.63099228
 28.90783755 33.50060741 38.93091711 29.95792821 13.07396811 29.02645881
 -4.08627871 21.99605107 -2.83233563 37.23344585 16.09241609 10.733097
  3.22778061 28.71168447 12.80751661 18.42169744 -9.06050998 20.88177485
 20.60478614 20.84669984 37.18740393 24.09101496  7.97539503 11.85159769
 24.8815598  -6.98872642 23.33833577 23.53189348  0.51912805 -3.55368512
  5.77141755  8.18553855 18.50983852 11.93007567 39.4186919  -4.89775946
  0.4438378  -1.93452411 22.65541627  2.66458013 13.31553864  2.2212796
 -2.05152082 -4.48124294 22.81647947 -3.09085243 -0.17088192  8.43625853
 31.04966149 -5.14493621 31.89724537 -5.19507961 38.82297325 13.43256008
 38.83805441 20.24227599 26.96317897 -8.04061039  4.14034813 -3.99017194
  4.80700988 -4.06361405  5.89915897 10.71314973 -6.79

In [29]:
below_freezing = temp_array < 0 #finding temperatures below 0 degree celsius 
#print(temp_array[below_freezing])
count_below_freezing = np.sum(below_freezing) # taking a count

print("Temperature below 0 degree celcius:", count_below_freezing)

Temperature below 0 degree celcius: 25


In [31]:
temp_array[below_freezing] = -5
#print(temp_array[below_freezing])
print(temp_array)

[17.4406752  25.75946832 20.1381688  17.24415915 11.18273997 22.29470565
 11.87936056 34.58865004 38.18313803  9.17207594 29.5862519  16.44474599
 18.40222805 36.27983191 -5.         -5.         -5.         31.63099228
 28.90783755 33.50060741 38.93091711 29.95792821 13.07396811 29.02645881
 -5.         21.99605107 -5.         37.23344585 16.09241609 10.733097
  3.22778061 28.71168447 12.80751661 18.42169744 -5.         20.88177485
 20.60478614 20.84669984 37.18740393 24.09101496  7.97539503 11.85159769
 24.8815598  -5.         23.33833577 23.53189348  0.51912805 -5.
  5.77141755  8.18553855 18.50983852 11.93007567 39.4186919  -5.
  0.4438378  -5.         22.65541627  2.66458013 13.31553864  2.2212796
 -5.         -5.         22.81647947 -5.         -5.          8.43625853
 31.04966149 -5.         31.89724537 -5.         38.82297325 13.43256008
 38.83805441 20.24227599 26.96317897 -5.          4.14034813 -5.
  4.80700988 -5.          5.89915897 10.71314973 -5.         24.62360597
 18.3

In [33]:
average_temperature = np.mean(temp_array)
print(average_temperature)

13.647387268217253


In [49]:
sorted_array = np.sort(temp_array)      # Sort in ascending order
reverse_array = sorted_array[::-1]      # Sort in decending order
#print(reverse_array)
top_temps = reverse_array[0:5]          # top 5 temperatures
print(top_temps)

[39.4186919  38.93091711 38.83805441 38.82297325 38.18313803]
